### ISSUE TITLE
ValueError: mask cannot be scalar.

### ISSUE THREAD

**Issue by MilenaTenorio** [logictensornetworks/logictensornetworks#24]
When I try define ltn.variable the following error is returned: 
```
    <ipython-input-11-51fc9a0fab79>:5 axioms *
        bb12_relation = ltn.variable("P",features[labels_position=="P"])
    C:\Users\Milena\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py:600 _slice_helper
        return boolean_mask(tensor=tensor, mask=slice_spec)
    C:\Users\Milena\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py:1365 boolean_mask
        raise ValueError("mask cannot be scalar.")

    ValueError: mask cannot be scalar.
```
Based on the code of **multiclass-multilabel.ipynb** I declare the first variable in the axioms function that returns the mentioned error:
`ltn.variable("P",features[labels_position=="P"])`

**Comment by sbadredd** [comment]
Hi Milena,

Can you send me the rest of your code so I can have a look?

At first glance, this seems to be a TensorFlow error, not related to ltn. If you write:
```
mask = (labels_position=="P")
tensor_P = features[mask]
x_P = ltn.variable("P", tensor_P)
```
- Does the error occur on the second line?
- If yes, can you check the value and type of `mask`, is it a `tf.Tensor` or a `np.ndarray`? It seems that in your case, `mask` could be just a boolean, which would cause the Tensorflow error `mask cannot be scalar` 
- If `mask` is not a `tf.Tensor`, you need to convert `labels_position` to a tensor beforehand. Also, try writing `mask = tf.equal(labels_position,"P")` to be more explicit

Hope it helps!

**Comment by MilenaTenorio** [comment]
Hi!

Thank you very much for the feedback, I will carry out the suggestions sent.
I can tell you what worked correctly in my code and share the link to access it

It will certainly help me

**Comment by MilenaTenorio** [comment]
Dear,

I add the code suggested:
```
    mask = (labels_position=="P")
    tensor_P = features[mask]
```
here:
   ` mask = (labels_position=="P") `-> return: FALSE
and
   `tensor_P = features[mask]` -> return:
```

ValueError: in converted code:

    <ipython-input-13-f5edfa7f8178>:8 axioms *
        tensor_P = features[mask]
    C:\Users\Milena\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py:600 _slice_helper
        return boolean_mask(tensor=tensor, mask=slice_spec)
    C:\Users\Milena\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py:1365 boolean_mask
        raise ValueError("mask cannot be scalar.")

    ValueError: mask cannot be scalar.
```

**Comment by MilenaTenorio** [comment]
I have made a summary of the code with information that I believe is relevant to the problem I am currently trying to solve. 
It's shared: [spatialrelation-resume.git](https://github.com/MilenaTenorio/spatialrelation-resume.git)

**Comment by MilenaTenorio** [comment]
Now I'll try to convert _labels_position_ to a tensor beforehand!

Thanks for your support!

**Comment by sbadredd** [comment]
With pleasure!

Writing something like: 
```
mask_P = tf.equal(tf.constant(labels_position),"P")
tensor_P = features[mask_P]
```
should help.

**Comment by sbadredd** [comment]
By the way, if the variable is empty (there are no values of label "P"), the code will return an error when you write your formula.
So maybe add something like:
```
axioms = []
if tf.reduce_sum(tf.cast(mask_P,tf.int32)) != 0:                                 # Only if x_P is not empty...
    axioms.append(Forall(x_P,p([x_P,class_P],training=training)))    # ... add the axiom
```

In the future, I might add some verifications for cases where the variables are empty

**Comment by MilenaTenorio** [comment]
Thank you very much for the support

**Comment by kwinHoney** [comment]
您的来信我已收到！
