### ISSUE TITLE
ltnw.term: evaluating a term after redeclaring its constants, variables or functions

### ISSUE THREAD

**Issue by sbadredd** [logictensornetworks/logictensornetworks#6]
The implementation of `ltnw.term` is incompatible with the redeclaration of constants, variables or functions

`ltnw.term` is looking at the result value previously stored in the global dictionary `ltnw.TERMS` rather than reconstructing the term

For instance, the code:
```
ltnw.variable('?x',[[3.0,5.0],[2.0,6.0],[3.0,9.0]])
print('1st call')
print('value of variable:\n'+str(ltnw.VARIABLES['var_x'].eval()))
print('value of term:\n'+str(ltnw.term('?x').eval()))

ltnw.variable('?x',[[3.0,10.0],[1.0,6.0]])
print('2nd call')
print('value of variable:\n'+str(ltnw.VARIABLES['var_x'].eval()))
print('value of term:\n'+str(ltnw.term('?x').eval()))
```

outputs:
```
1st call
value of variable:
[[3. 5.]
 [2. 6.]
 [3. 9.]]
value of term:
[[3. 5.]
 [2. 6.]
 [3. 9.]]

2nd call
value of variable:
[[ 3. 10.]
 [ 1.  6.]]
value of term:
[[3. 5.]
 [2. 6.]
 [3. 9.]]
```

**Comment by dahvid** [comment]
Yes, this looks like it could have caused the closed issue "regression_linear tutorial gives wrong result".

**Comment by sbadredd** [comment]
Closing because we are not maintaining the [older version](https://github.com/logictensornetworks/logictensornetworks/tree/v1) of LTN anymore.

If needed, one solution is to reset `ltnw.TERMS = {}` if you happen to redeclare a symbol. 🙂
