### ISSUE TITLE
Check of number_of_features_or_feed of ltn.variable

### ISSUE THREAD

**Issue by ivanDonadello** [logictensornetworks/logictensornetworks#7]
Hello,

when we define a variable with `ltnw.variable('name', num_feats)` if num_feats is a numpy.int_ ltn instantiates a variable with a wrong shape. I guess this is due to the control at line 185 here [https://github.com/logictensornetworks/logictensornetworks/blob/master/logictensornetworks.py](url), as a numpy.int_ is not an int. A check like this `if type(number_of_features_or_feed) is int or type(number_of_features_or_feed) is numpy.int_` should work.

**Comment by mspranger** [comment]
Thanks Ivan! Let me check and update this within the next few days

**Comment by sbadredd** [comment]
Closing because we are not maintaining the [older version ](https://github.com/logictensornetworks/logictensornetworks/tree/v1) of LTN anymore
The solution pointed out by Ivan should work though 👍
